# Generated by Django 5.2.8 on 2026-04-20 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(db_column='coordinator_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='FYPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_matric_id', models.CharField(blank=True, max_length=50, verbose_name='Student ID')),
                ('title', models.CharField(max_length=255)),
                ('fyp_stage', models.CharField(choices=[('FYP1', 'Final Year Project 1'), ('FYP2', 'Final Year Project 2')], default='FYP1', max_length=10)),
                ('co_supervisor', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosupervised_projects', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('examiner', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_projects', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fyp_title', models.TextField()),
                ('supervisor_name', models.CharField(max_length=255)),
                ('lecturer', models.ForeignKey(db_column='lecturer_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'milestone_forms',
            },
        ),
        migrations.CreateModel(
            name='MilestoneEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_number', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.milestoneforms')),
            ],
            options={
                'db_table': 'milestone_entries',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('coordinator', 'Coordinator')], default='student', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('programme', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id_no', models.CharField(max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('programme', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('project_category', models.CharField(max_length=50)),
                ('proposed_project_title', models.TextField()),
                ('detail_description', models.TextField()),
                ('detail_problem', models.TextField()),
                ('detail_value', models.TextField()),
                ('detail_scope', models.TextField()),
                ('detail_similar_system', models.TextField()),
                ('detail_features', models.TextField()),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_supervisor', models.ForeignKey(blank=True, db_column='co_supervisor_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(db_column='student_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(db_column='supervisor_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('lecturer', models.ForeignKey(db_column='lecturer_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, to='api.submissions')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='SupervisorQuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_total', models.IntegerField()),
                ('lecturer', models.OneToOneField(db_column='lecturer_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supervisor_quotas',
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('examiners', models.ManyToManyField(limit_choices_to={'profile__role': 'lecturer'}, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fypproject')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_days', to='api.course')),
            ],
            options={
                'unique_together': {('date', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TimetableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('examiner', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_bookings', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(limit_choices_to={'profile__role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fypproject')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'venue')},
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api.course')),
            ],
            options={
                'unique_together': {('name', 'course')},
            },
        ),
    ]
