# Generated by Django 5.2.8 on 2026-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestoneentries',
            options={'ordering': ['milestone_number']},
        ),
        migrations.AddField(
            model_name='milestoneentries',
            name='max_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestoneentries',
            name='milestone_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
