# Generated by Django 5.2.8 on 2026-05-07 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_milestoneentries_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailable_slots', models.JSONField(blank=True, default=list, help_text="A list of 30-minute time slots (e.g., 'HH:mm') where the lecturer is unavailable.")),
                ('lecturer', models.ForeignKey(limit_choices_to=models.Q(('profile__role', 'lecturer'), ('profile__role', 'coordinator'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presentation_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.presentationday')),
            ],
            options={
                'ordering': ['presentation_day__date', 'lecturer__profile__full_name'],
                'unique_together': {('lecturer', 'presentation_day')},
            },
        ),
    ]
