# Generated by Django 5.2.8 on 2026-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lecturerpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='detail_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='detail_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='detail_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='detail_similar_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='detail_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
