# Generated by Django 5.2.8 on 2026-05-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_submissions_detail_description_and_more'),
    ]

    operations = [
    ]
