# Generated by Django 5.2.8 on 2026-05-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_course_to_programme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Programme',
        ),
        migrations.RenameField(
            model_name='fypproject',
            old_name='course',
            new_name='programme',
        ),
        migrations.RenameField(
            model_name='presentationday',
            old_name='course',
            new_name='programme',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='course',
            new_name='programme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='presentationday',
            unique_together={('date', 'programme')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'programme')},
        ),
    ]
