# Generated by Django 5.2.8 on 2026-05-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_course_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.programme'),
        ),
    ]
