# Generated by Django 5.2.8 on 2026-05-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programme'),
        ),
    ]
