# Generated by Django 5.2.8 on 2026-05-15 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rubrictemplate_rubricmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturerpreference',
            options={'ordering': ['presentation_slot__date', 'lecturer__profile__full_name']},
        ),
        migrations.AlterField(
            model_name='lecturerpreference',
            name='unavailable_slots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PresentationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue_name', models.CharField(max_length=100)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programme')),
            ],
            options={
                'unique_together': {('programme', 'date', 'venue_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lecturerpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lecturerpreference',
            name='presentation_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.presentationslot'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturerpreference',
            unique_together={('lecturer', 'presentation_slot')},
        ),
        migrations.RemoveField(
            model_name='lecturerpreference',
            name='presentation_day',
        ),
    ]
