# Generated by Django 5.2.8 on 2026-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_lecturerpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fypproject',
            name='fyp_stage',
            field=models.CharField(choices=[('PROPOSAL', 'Proposal Defense'), ('FYP1', 'Final Year Project 1'), ('FYP2', 'Final Year Project 2')], default='FYP1', max_length=20),
        ),
    ]
